development:
  adapter: postgresql
  encoding: unicode
  database: dogpark_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dogpark_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dogpark_production
  pool: 5
  username:
  password:
